# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
